import Foundation

/// Streaming QRS detector — Swift port of `server/ecg_algorithms.py`.
///
/// This is a direct transcription: identical filter coefficients, window
/// lengths, thresholds and order of operations, so the phone and the server
/// produce the same beats from the same signal. `EquivalenceTests` asserts that
/// against reference vectors generated by the Python implementation — run it
/// after touching either side, because a silent divergence between edge and
/// cloud results is the most dangerous bug this project can have.
///
/// Reference: J. Pan and W. J. Tompkins, "A Real-Time QRS Detection Algorithm",
/// IEEE Trans. Biomed. Eng., BME-32(3), pp. 230–236, 1985.
final class PanTompkins {

    /// One detected heartbeat plus the features the classifier needs.
    struct Beat {
        var index: Int = 0          // sample number of the R peak
        var rrPrev: Double = 0      // seconds to the previous R peak
        var rrNext: Double = 0      // seconds to the next R peak
        var rrMean: Double = 0      // mean of the last 8 RR intervals
        var width: Double = 0       // effective QRS duration, seconds
        var amplitude: Double = 0   // peak-to-peak of the bandpassed QRS
        var widthMean: Double = 0   // running mean width of normal beats
        var ampMean: Double = 0     // running mean amplitude of normal beats
        var corr: Double = 0        // correlation with the running template
        var label: String = "?"
        var confidence: Double = 0

        var bpm: Double { rrPrev > 0 ? 60.0 / rrPrev : 0 }
    }

    // 5–15 Hz Butterworth bandpass, two cascaded biquads, fs = 250 Hz.
    // scipy.signal.butter(2, [5,15], btype='bandpass', fs=250, output='sos')
    private static let sos: [[Double]] = [
        [0.013359200027856493, 0.026718400055712986, 0.013359200027856493,
         -1.6813538569552235, 0.779892143960428],
        [1.0, -2.0, 1.0,
         -1.8795935958755112, 0.8987098877918257],
    ]

    /// Transposed direct form II — numerically well behaved, two state variables.
    private final class Biquad {
        let b0, b1, b2, a1, a2: Double
        var z1 = 0.0, z2 = 0.0
        init(_ c: [Double]) { b0 = c[0]; b1 = c[1]; b2 = c[2]; a1 = c[3]; a2 = c[4] }
        func process(_ x: Double) -> Double {
            let y = b0 * x + z1
            z1 = b1 * x - a1 * y + z2
            z2 = b2 * x - a2 * y
            return y
        }
    }

    private let fs: Double
    private var stages: [Biquad]

    private let refractory: Int
    private let tWaveWin: Int
    private let intWin: Int
    private let hist: Int
    private let templateHalf: Int
    private let learning: Int

    private var deriv = [Double](repeating: 0, count: 5)
    private var intBuf: [Double]
    private var intIdx = 0
    private var intSum = 0.0

    private var filtHist: [Double]
    private var n = 0

    private var spki = 0.0
    private var npki = 0.0
    private var threshold1 = 0.0

    private var prevInt = 0.0
    private var rising = false
    private var peakVal = 0.0
    private var peakIdx = 0

    private static let noQRS = Int.min / 2
    private var lastQrs = PanTompkins.noQRS
    private var rrHist = [Double]()
    private var rrMean = 0.0

    private var template: [Double]?
    private var widthMean = 0.0
    private var ampMean = 0.0

    private var pending: Beat?

    init(sampleRate: Double = 250.0) {
        fs = sampleRate
        stages = PanTompkins.sos.map { Biquad($0) }
        refractory   = Int(0.20 * sampleRate)
        tWaveWin     = Int(0.36 * sampleRate)
        intWin       = Int(0.15 * sampleRate)
        hist         = Int(2.0 * sampleRate)
        templateHalf = Int(0.08 * sampleRate)
        learning     = Int(2.0 * sampleRate)
        intBuf   = [Double](repeating: 0, count: Int(0.15 * sampleRate))
        filtHist = [Double](repeating: 0, count: Int(2.0 * sampleRate))
    }

    /// Feed one sample in millivolts. Returns a finished `Beat`, or `nil`.
    func process(_ sample: Double) -> Beat? {
        let i = n
        var f = sample
        for s in stages { f = s.process(f) }
        filtHist[mod(i, hist)] = f

        // 5-point derivative
        deriv.removeFirst()
        deriv.append(f)
        let d = (-deriv[0] - 2 * deriv[1] + 2 * deriv[3] + deriv[4]) / 8.0

        intSum -= intBuf[intIdx]
        intBuf[intIdx] = d * d
        intSum += intBuf[intIdx]
        intIdx = (intIdx + 1) % intWin
        let integ = intSum / Double(intWin)

        n += 1

        if i < learning {
            if integ > spki { spki = integ }
            npki = 0.95 * npki + 0.05 * integ
            threshold1 = npki + 0.25 * (spki - npki)
            prevInt = integ
            return nil
        }

        var beat: Beat?
        if integ > prevInt {
            rising = true
            if integ > peakVal { peakVal = integ; peakIdx = i }
        } else if rising {
            rising = false
            beat = evaluatePeak(peakVal, peakIdx)
            peakVal = 0
        }
        prevInt = integ
        return beat
    }

    /// Emit the final buffered beat when the stream ends.
    func flush() -> Beat? {
        let b = pending
        pending = nil
        return b
    }

    var heartRate: Double { rrMean > 0 ? 60.0 / (rrMean / fs) : 0 }

    // MARK: - Internals

    private func mod(_ a: Int, _ b: Int) -> Int { ((a % b) + b) % b }

    private func histGet(_ idx: Int) -> Double {
        if idx < 0 || idx <= n - hist || idx > n { return 0 }
        return filtHist[mod(idx, hist)]
    }

    private func evaluatePeak(_ peak: Double, _ idx: Int) -> Beat? {
        if peak > threshold1 {
            if idx - lastQrs < refractory { return nil }
            if rrMean > 0 && idx - lastQrs < tWaveWin && isTWave(idx) {
                npki = 0.125 * peak + 0.875 * npki
                threshold1 = npki + 0.25 * (spki - npki)
                return nil
            }
            spki = 0.125 * peak + 0.875 * spki
            threshold1 = npki + 0.25 * (spki - npki)
            return registerQRS(idx)
        }
        npki = 0.125 * peak + 0.875 * npki
        threshold1 = npki + 0.25 * (spki - npki)
        return nil
    }

    /// T waves rise more slowly than QRS complexes.
    private func isTWave(_ idx: Int) -> Bool {
        let sNew = maxSlope(idx)
        let sOld = maxSlope(lastQrs)
        return sOld > 0 && sNew < 0.5 * sOld
    }

    private func maxSlope(_ idx: Int) -> Double {
        var m = 0.0
        var k = idx - Int(0.05 * fs)
        while k <= idx {
            let s = abs(histGet(k) - histGet(k - 1))
            if s > m { m = s }
            k += 1
        }
        return m
    }

    private func registerQRS(_ detectIdx: Int) -> Beat? {
        // Undo the derivative + integrator delay, then find the true extremum.
        let guessIdx = detectIdx - (intWin / 2 + 2)
        var rIdx = guessIdx
        var rVal = 0.0
        var k = guessIdx - Int(0.05 * fs)
        while k <= guessIdx + Int(0.05 * fs) {
            let v = abs(histGet(k))
            if v > rVal { rVal = v; rIdx = k }
            k += 1
        }

        // A bandpassed QRS is biphasic, so "largest |sample|" lands on R for one
        // beat and on S for the next. That jitter would wreck the morphology
        // feature, so once a template exists we slide ±45 ms and keep the lag
        // with the best correlation. The span must exceed the R-to-S spacing, or
        // an estimate that landed on S can never slide back onto R.
        var corr = 1.0
        if let tmpl = template {
            let span = Int(0.045 * fs)
            var bestC = -2.0
            var bestK = rIdx
            var j = rIdx - span
            while j <= rIdx + span {
                let c = PanTompkins.pearson(window(j), tmpl)
                if c > bestC { bestC = c; bestK = j }
                j += 1
            }
            rIdx = bestK
            corr = bestC
        }

        let rr = (lastQrs > PanTompkins.noQRS) ? rIdx - lastQrs : 0
        lastQrs = rIdx
        if rr > 0 && Double(rr) < 2.0 * fs {
            rrHist.append(Double(rr))
            if rrHist.count > 8 { rrHist.removeFirst() }
            rrMean = rrHist.reduce(0, +) / Double(rrHist.count)
        }

        var b = Beat()
        b.index = rIdx
        b.rrPrev = rr > 0 ? Double(rr) / fs : 0
        b.rrMean = rrMean > 0 ? rrMean / fs : 0
        b.width = qrsWidth(rIdx)
        b.amplitude = amplitude(rIdx)
        b.corr = corr
        b.widthMean = widthMean != 0 ? widthMean : b.width
        b.ampMean = ampMean != 0 ? ampMean : b.amplitude
        b.rrNext = 0

        updateTemplate(rIdx, b)

        // Hold each beat back one cycle so the classifier can see the pause that
        // FOLLOWS it — the compensatory pause is what separates a PVC from an
        // atrial premature beat.
        var out = pending
        pending = b
        if out != nil { out!.rrNext = b.rrPrev }
        return out
    }

    /// Effective QRS duration as the energy spread about R:
    ///   width = 2·√( Σ f²[k]·(k−r)² / Σ f²[k] ) / fs
    /// A threshold-crossing width is bimodal here because the bandpassed signal
    /// rings; the second moment is smooth, threshold-free and energy-weighted.
    private func qrsWidth(_ rIdx: Int) -> Double {
        let half = Int(0.08 * fs)
        var num = 0.0, den = 0.0
        var k = rIdx - half
        while k <= rIdx + half {
            let v = histGet(k)
            let e = v * v
            let dd = Double(k - rIdx)
            num += e * dd * dd
            den += e
            k += 1
        }
        if den <= 0 { return 0 }
        return 2.0 * (num / den).squareRoot() / fs
    }

    private func amplitude(_ rIdx: Int) -> Double {
        var lo = 1e18, hi = -1e18
        var k = rIdx - Int(0.06 * fs)
        while k <= rIdx + Int(0.06 * fs) {
            let v = histGet(k)
            if v < lo { lo = v }
            if v > hi { hi = v }
            k += 1
        }
        return hi - lo
    }

    private func window(_ rIdx: Int) -> [Double] {
        var out = [Double](repeating: 0, count: 2 * templateHalf + 1)
        for j in 0..<out.count { out[j] = histGet(rIdx - templateHalf + j) }
        return out
    }

    /// Only average in beats that still look normal, so a run of ectopics cannot
    /// drag the template toward the abnormal morphology.
    private func updateTemplate(_ rIdx: Int, _ b: Beat) {
        let w = window(rIdx)
        guard var tmpl = template else {
            template = w
            widthMean = b.width
            ampMean = b.amplitude
            return
        }
        if b.corr > 0.8 {
            let a = 0.9
            for j in 0..<tmpl.count { tmpl[j] = a * tmpl[j] + (1 - a) * w[j] }
            template = tmpl
            widthMean = a * widthMean + (1 - a) * b.width
            ampMean = a * ampMean + (1 - a) * b.amplitude
        }
    }

    static func pearson(_ a: [Double], _ b: [Double]) -> Double {
        let m = min(a.count, b.count)
        if m == 0 { return 0 }
        var ma = 0.0, mb = 0.0
        for i in 0..<m { ma += a[i]; mb += b[i] }
        ma /= Double(m)
        mb /= Double(m)
        var num = 0.0, sa = 0.0, sb = 0.0
        for i in 0..<m {
            let da = a[i] - ma
            let db = b[i] - mb
            num += da * db
            sa += da * da
            sb += db * db
        }
        if sa <= 0 || sb <= 0 { return 0 }
        return num / (sa * sb).squareRoot()
    }
}
